export type TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_MENU: TOGGLE_MENU = "TOGGLE_MENU";

export type OPEN_RIGHT_PANEL = "OPEN_RIGHT_PANEL";
export const OPEN_RIGHT_PANEL: OPEN_RIGHT_PANEL = "OPEN_RIGHT_PANEL";

export type CLOSE_RIGHT_PANEL = "CLOSE_RIGHT_PANEL";
export const CLOSE_RIGHT_PANEL: CLOSE_RIGHT_PANEL = "CLOSE_RIGHT_PANEL";
