export type TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_MENU: TOGGLE_MENU = "TOGGLE_MENU";

export type TOGGLE_RIGHT_PANEL = "TOGGLE_RIGHT_PANEL";
export const TOGGLE_RIGHT_PANEL: TOGGLE_RIGHT_PANEL = "TOGGLE_RIGHT_PANEL";
