type SITES_TOGGLE_SWITCH_RIGHT_PANE = "SITES_TOGGLE_SWITCH_RIGHT_PANE";
const SITES_TOGGLE_SWITCH_RIGHT_PANE: SITES_TOGGLE_SWITCH_RIGHT_PANE = "SITES_TOGGLE_SWITCH_RIGHT_PANE";

export default SITES_TOGGLE_SWITCH_RIGHT_PANE;
