import IDashboardResponseResult from "../duck/operations/interfaces/IDashboardResponseResult";
import IJobModel from "../../../models/jobs/IJobModel";
import ISiteModel from "../../../models/sites/ISiteModel";

export default class DashboardDataShim {
    private static jobs: IJobModel[] = [
        {
            id: "456",
            number: "JB-1000",
            name: "foo",
            siteId: "909876",
            status: "Active",
            description: "This is a job.",
            tenantId: "100",
            progress: 10,
            numberOfUnitsInProgress: 2,
            numberOfUnitsCompleted: 1,
            numberOfPipingInProgress: 0,
            numberOfPipingCompleted: 0,
            numberOfFiles: 0,
            createdBy: "Jeff",
            createdAt: "2000-00-00T11:11:00+00:00",
            updatedBy: "Jeff",
            updatedAt: "2000-00-00T11:11:00+00:00",

        },
        {
            id: "123",
            number: "JB-3333",
            name: "bar",
            siteId: "909877",
            status: "Active",
            description: "This is another job.",
            tenantId: "100",
            progress: 0,
            numberOfUnitsInProgress: 0,
            numberOfUnitsCompleted: 0,
            numberOfPipingInProgress: 8,
            numberOfPipingCompleted: 3,
            numberOfFiles: 16,
            createdBy: "Jeff",
            createdAt: "1999-11-19T11:11:11+00:00",
            updatedBy: "Jeff",
            updatedAt: "1999-11-19T11:11:11+00:00",
        },
        {
            id: "888",
            number: "JB-88888888",
            name: "baz",
            siteId: "909876",
            status: "Active",
            description: "Maybe this is the last job?",
            tenantId: "100",
            progress: 90,
            numberOfUnitsInProgress: 0,
            numberOfUnitsCompleted: 9,
            numberOfPipingInProgress: 1,
            numberOfPipingCompleted: 0,
            numberOfFiles: 1,
            createdBy: "Jeff",
            createdAt: "2018-09-01T19:11:11+00:00",
            updatedBy: "Jeff",
            updatedAt: "2018-09-01T19:11:11+00:00",
        },
    ];

    private static sites: ISiteModel[] = [
        {
            id: "0",
            tenantId: "100",
            name: "My house",
            status: "Active",
            description: "This is my house.",
            street: "99 SE 10th St",
            city: "Vancouver",
            state: "British Columbia",
            postalCode: "A1A 3D3",
            country: "Canada",
            phoneNumber: "18001001000",
            numberOfUnits: 1,
            numberOfPiping: 2,
            numberOfActiveJobs: 3,
            numberOfCompletedJobs: 4,
            numberOfArchivedJobs: 5,
            numberOfTotalJobs: 6,
            numberOfFiles: 7,
            createdBy: "Jeff",
            createdAt: "2018-01-05T19:11:11+00:00",
            updatedBy: "Jeff",
            updatedAt: "2018-01-05T19:11:11+00:00",
        },
        {
            id: "00",
            tenantId: "100",
            name: "My office",
            status: "Active",
            description: "Please take a seat.",
            street: "1188 West Pender St",
            city: "Vancouver",
            state: "British Columbia",
            postalCode: "B1B 8D8",
            country: "Canada",
            phoneNumber: "18002002000",
            numberOfUnits: 10,
            numberOfPiping: 20,
            numberOfActiveJobs: 30,
            numberOfCompletedJobs: 40,
            numberOfArchivedJobs: 50,
            numberOfTotalJobs: 60,
            numberOfFiles: 70,
            createdBy: "Jeff",
            createdAt: "2018-01-01T19:11:11+00:00",
            updatedBy: "Jeff",
            updatedAt: "2018-01-01T19:11:11+00:00",
        },
    ];

    public static getData(): IDashboardResponseResult {
        return {
            activeJobs: DashboardDataShim.jobs,
            activeSites: DashboardDataShim.sites
        };
    }
}
