type DASHBOARD_CLOSE_RIGHT_PANE = "DASHBOARD_CLOSE_RIGHT_PANE";
const DASHBOARD_CLOSE_RIGHT_PANE: DASHBOARD_CLOSE_RIGHT_PANE = "DASHBOARD_CLOSE_RIGHT_PANE";

export default DASHBOARD_CLOSE_RIGHT_PANE;
